spring.application.name=Task-Tracker


# Database Connection Settings

spring.datasource.url=jdbc:mysql://localhost:3306/task_Tracker
spring.datasource.username=root
spring.datasource.password=JOp97)#?6nmu

# JPA / Hibernate Configuration

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true